project:
  type: book
  output-dir: docs
  post-render: includes/restore-cname.R

book:
  title: "Efficient Machine Learning with R"
  subtitle: "Low-Compute Predictive Modeling with tidymodels"
  author: "Simon P. Couch"
#  date: "3/21/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Fundamentals"
      chapters:
      - models.qmd
      - parallelism.qmd
      - search.qmd
      - submodel.qmd
    - part: "Beyond the Basics"
      chapters:
      - preprocessing.qmd
      - sparsity.qmd
      - stacking.qmd
    - references.qmd
  google-analytics: "G-C5VQ0DLJJW"
  repo-url: "https://github.com/simonpcouch/emlwr"
    
bibliography: references.bib

format:
  html:
    theme: [cosmo, includes/emlwr.scss]
    mainfont: 'Montserrat'
    fig-width: 6
    fig-height: 4.25
    fig-align: center
    tbl-cap-location: bottom
    fig-cap-location: bottom
    message: false
    warning: false
    
  pdf:
    documentclass: scrreprt

filters:
  - shinylive
  
editor: visual
